### ISSUE TITLE
[Pan] Allow to specify a mouse button

### ISSUE THREAD

**Issue by vallsv** [silx-kit/h5web#1120]
Hi,

I want to implement silx interaction in the plot.

It sounds like the `Pan` interaction is working for any mouse button.

It would be good to limit the interaction to a specific button.

And as it's low cost this used button could be selected by property.

As result i will be able to create a `Pan` interaction with a middle mouse button only.

This start to be an important feature for me, as the plot is about to be integrated and used in production.
https://gitlab.esrf.fr/ui/daiquiri-tomo/-/issues/115

**Comment by axelboc** [comment]
As per https://github.com/silx-kit/h5web/issues/1121#issuecomment-1135987700, you're right that it should definitely not be possible to pan with the right mouse button.

When it comes to the middle button, I think I agree with you that this needs to be configurable via a prop so that you can have two `Pan` components in your canvas: one bound to the left button (and enabled conditionally based on the tool selected by the user) and the other to the middle button. I think a simple boolean prop, for instance called `withMiddleBtn`, could do the trick.

One small implementation challenge comes from having to take into account mouse buttons in our `InteractionsProvider`'s `shouldInteract` function.

**Comment by vallsv** [comment]
While i can do such change of the behaviour by description, it's fine to me. Anyway it's a prop, or a new component.

**Comment by loichuder** [comment]
With #1129, panning with the right mouse button no longer works and a prop `button` can be passed to `Pan` to set it to `Left` (default) or `Middle`
