### ISSUE TITLE
Search for string in object names

### ISSUE THREAD

**Issue by bmaranville** [silx-kit/h5web#1348]
### Is your feature request related to a problem?

HDF5 is *hierarchical*, and sometimes users are looking for a particular group or dataset by name, and don't know where to start.  Given that many NeXus files are in practice deeply nested and contain hundreds of groups and datasets, this can be quite a challenge and an annoyance for using NeXus files.
 

### Requested solution or feature

Apparently at the SNS there is a search capability in their web frontend for NeXus files, that allows finding a dataset/group by substring within a given file.  Users have requested that this functionality be implemented in H5Web as well.  In the SNS implementation, they seem to present a filtered tree which only contains paths for which the substring is matched.

#### Description of feature:
User types a string into a search box, and matched paths within the file are presented.  It could be a clickable list of matching paths, or a filtered tree, or ...

### Alternatives you've considered

At the moment, search can be clumsily achieved by using the browser's search and exploding all the paths in the HDF5 tree.  An option to explode all paths is not available.

### Additional context

Clearly implementing this without modifying the existing API of access tools like h5grove or h5wasm will be slow and inefficient, requiring recursive lookups from the frontend.  

An ancillary requirement of this feature then also be to add either a search function to the access APIs, or a function to simply return a list of all paths in the file.  Either of those can be efficiently implemented in h5py or h5wasm or ... using the underlying visititems functionality that maps directly onto the HDF5 C api.

**Comment by loichuder** [comment]
For insight, this was already discussed for silx at some point: https://github.com/silx-kit/silx/issues/3575

**Comment by loichuder** [comment]
Hello @bmaranville 

I am working on a prototype at https://github.com/silx-kit/h5web/pull/1358. 

Here is the search in action:
[Screencast from 08-02-2023 13:43:00.webm](https://user-images.githubusercontent.com/42204205/217533240-991f931a-b90f-4b22-b5e7-36f24fdc6875.webm)

Among the rough edges, you can see that we settled for now on **a UI with a Previous/Next button to reach matches of the search** rather than filtering paths in the explorer.

The search for matches is not by the back-end/provider but by the React component. **The only job of the provider is to return a list of paths on which the search is done**. In this case, I added an endpoint to this purpose in `h5grove` that is called by `H5GroveProvider`.

Are these decisions sensible for you ? Will they answer your need ? 

This is still in early stages so I will be happy to have your opinion to further shape the feature.

**Comment by loichuder** [comment]
Glad that we agree on the backend implementation :slightly_smiling_face: 

I will make further tries for the UI part to see if I manage to have something more user-friendly.

**Comment by bmaranville** [comment]
I can add a function to h5wasm that efficiently returns a list of all paths in a file.

**Comment by bmaranville** [comment]
added Group.paths() in v0.4.10 of h5wasm, published to npm.  Returns a list of all links below the group in the hdf5 tree.  Does not include the group name itself.  Note that if run from the root group (the h5wasm.File object), it will return all paths in the file, but without a leading `/` in the path, and without including the root path `/`

**Comment by loichuder** [comment]
Just tried, it works great ! Thanks a lot :slightly_smiling_face: 

On my side, I changed a bit the UI to have a separate tab for the search that filters paths (a bit like VSCode does it):

[Screencast from 20-02-2023 10:38:20.webm](https://user-images.githubusercontent.com/42204205/220074180-36d8fee5-8a63-4ad3-9d26-9fd50d72f6c7.webm)

It is still a bit rough: we can notably improve the display of filtering paths but I like this better and I think this goes the right way.
