### ISSUE TITLE
[HeatmapVis] Stories with custom axis values appear broken

### ISSUE THREAD

**Issue by axelboc** [silx-kit/h5web#1423]
The heatmap itself doesn't appear on the following stories (only the canvas):

- https://h5web-docs.panosc.eu/?path=/story/visualizations-heatmapvis--axis-values
- https://h5web-docs.panosc.eu/?path=/story/visualizations-heatmapvis--descending-axis-values

**Comment by loichuder** [comment]
I think it is due to the big mismatch between the extent of abscissas and the one of ordinates. When using `aspect: equal` in the stories, the heatmap is extremely thin which makes it barely visible. 

It displays fine with `aspect: auto`: https://h5web-docs.panosc.eu/?path=/story/visualizations-heatmapvis--axis-values&args=aspect:auto
