### ISSUE TITLE
Show file size

### ISSUE THREAD

**Issue by LogWell** [silx-kit/h5web#1451]
May I ask how to display the size of each item in the h5 file, similar to a zip file?

![image](https://github.com/silx-kit/h5web/assets/34391447/b598bfa3-dbad-4235-b2c4-a712ebe2e1bd)

![image](https://github.com/silx-kit/h5web/assets/34391447/1b72df8d-edba-4906-a94c-847a8d7726c5)

**Comment by axelboc** [comment]
For datasets, you can easily switch to "Inspect" and get a good approximation of the number of bytes by looking at the dimensions and datatype. However, getting an exact value to display in the UI is problematic because (to my knowledge) there's no low-level API to access this information in HDF5.

For groups, this is even more problematic, because the computation would require recursing through the entire hierarchy of each group, which has the potential to be very slow for large HDF5 files with thousands of groups and datasets on slow file systems.

May I ask why you would like to see the sizes of the datasets/groups in the explorer? What are you looking for? What kind of data are you working with? In what context?

**Comment by LogWell** [comment]
I want to generate some data with a textured mesh for training a neural network.

My approach is to treat `HDF5` as a file system, and then generate different types of data (such as rendering color / depth / normal maps, generating meshes and voxels, etc.), and write/append these data through `with h5py.File(filename, 'r+') as h5f:` into this `h5` file.

But after adding some newly generated data, I found that the file was a bit large, so I checked which large files there were and if there was a problem somewhere.

For example, directly save the image in `uint8` format, the resulting file is still very large, even with the compression parameter. At this time, I need to find a way to encode (as `jpg`) and save it, which will greatly reduce the file size.

I ask this question because opening `h5` files with `HDFView` or `H5Web` is very similar to opening `zip` files.

**Comment by LogWell** [comment]
https://github.com/h5py/h5py/issues/2283

**Comment by axelboc** [comment]
Thanks for sharing your use case in more details. So the discussion on the h5py repo confirms that computing the size of datasets and groups is not technically feasible ... at least not in a way that accurately reflects the real size on disk.
