### ISSUE TITLE
Error: Expected dataset to have numeric type

### ISSUE THREAD

**Issue by kdheepak** [silx-kit/h5web#1523]
### Describe the bug

When using the `signal` attribute on a group, I get a `Expected data to be numeric` error message. This seems to work for other HDF5 files though.

In the screenshots below, the left hand side is the h5web interface for [`chopper.nxs`](https://github.com/prjemian/punx/blob/327192fb5ea0edf69699881c531ad4bc5c12b8d9/punx/data/chopper.nxs) and the right hand side is the file that we are trying to create with the `signal` attribute on one of the groups:

![image](https://github.com/silx-kit/h5web/assets/1813121/1f0a0482-fc68-45b7-badd-3fe154800412)
![image](https://github.com/silx-kit/h5web/assets/1813121/6a57c848-3825-4bf9-954c-3e0df5c572ab)

So I don't believe this is a bug necessarily. I think this is us incorrectly setting some attribute?

### To Reproduce

1. Download this file

[output-testing.zip](https://github.com/silx-kit/h5web/files/13298738/output-testing.zip)

2.  Open this file in h5web. 
3. Click on `nexus_entry/nx_data`

### Expected behaviour

We expect the plot to be seen because the `signal` attribute points to `Dmd2`

### Screenshots

The plot shows up as expected when using `nexus_entry/nx_data/Dmd2` 

![image](https://github.com/silx-kit/h5web/assets/1813121/7ae7e1bd-5db1-4252-91eb-7d56c44a058f)

but does not work when clicking on the `nexus_entry/nx_data` group

### Context

- OS: Windows
- Browser: VSCode

**Comment by loichuder** [comment]
Hello @kdheepak 

First, let me apologize, you are clearly ahead of us on https://github.com/silx-kit/h5web/issues/1441 since you now have a correctly structured NeXus file while we didn't make the relevant changes in H5Web :sweat_smile: 

In this case, it comes from the `axes` datasets that store string rather than numerical values   (the `signal` and your NeXus structure is fine). 

We don't support **yet** `axes` containing strings . For that, we need to do the changes mentioned in https://github.com/silx-kit/h5web/issues/1441#issuecomment-1588960762 so that

> The axes would still show indices, but the tooltip would display the real axis value

Thanks for the report, that will motivate us to keep working on that :wink:

**Comment by loichuder** [comment]
Just to be crystal clear: further progress on this will be tracked at #1441
