### ISSUE TITLE
Highlight selected dataset in explorer

### ISSUE THREAD

**Issue by axelboc-esrf** [silx-kit/h5web#19]
When selecting a dataset then a group or datatype, the dataset remains displayed in the visualizer. Perhaps this should be made clear by highlighting the dataset that was last selected in the explorer even when another group or datatype is also highlighted.

**Comment by loichuder** [comment]
What about displaying the dataset name above its values in the Datavisualiser ?

**Comment by axelboc** [comment]
Yeah, I removed it for technical reasons, but it might be useful to bring it back.

I'm a bit reluctant, though, because I feel like it would reduce the space available for the visualization, which is what really matters. We could put the name inside the new visualization selector tab bar, but I was thinking of making this bar vertical exactly for this reason. 

What I have in mind for the tab bar is a floating icon panel, similar to the latest Start Menu design on Windows, which expands on hover:

![image](https://user-images.githubusercontent.com/2936402/76857542-f3cc9000-6855-11ea-8a6c-24ae4d641ab3.png)

![image](https://user-images.githubusercontent.com/2936402/76857553-fb8c3480-6855-11ea-8fda-43613151e7b8.png)

**Comment by loichuder** [comment]
Ok, let's put your idea in practice and see how it goes !

**Comment by loichuder** [comment]
Chose to go with #40 instead.
