### ISSUE TITLE
Copying/exporting datasets

### ISSUE THREAD

**Issue by axelboc-esrf** [silx-kit/h5web#35]
The goal is to be able to use a dataset somewhere else, like in a Jupyter Notebook. The copy could be done either by reference or by value. The export could be to CSV or other raw formats.

**Comment by axelboc** [comment]
User feedback suggested allowing rows/columns of the Matrix visualization to be selected and copied. Because the grid is virtualized, we can't rely on default text selection and copy; we'd have to provide a specific UI for this and make use of the [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API).

For the UI:
- We could have a button in the toolbar to copy the whole table, another to copy the current slice for 3D+ datasets, and an input of sorts to enter a range to copy (e.g. `0,0,:,:`).
- We could allow selection of visible rows and columns with click-and-drag -- when a selection is active, we could then show a button in the toolbar to copy the selection (and another button to clear the selection).
- We could allow copying a single row/column by showing a button in the row/column header cell on hover.
- ...

**Comment by axelboc** [comment]
> User feedback suggested allowing rows/columns of the Matrix visualization to be selected and copied. 

We won't support this behaviour.

However, we should allow users to export data from other visualizations:

- Line as CSV
- Heatmap as CSV
- NxSpectrum as CSV, with custom axis values, and with axis label and plot title as column headers
- NxImage as CSV -- exact format to be discussed
- TIFF and NPY formats should also be considered

**Comment by axelboc** [comment]
We're going to implement TIFF encoding in H5Grove (i.e. in the back-end) and use provider-level feature detection to determine whether to show the export button in the toolbars.

Once we have the feature detection system implemented, we'll be able to do the same for the CSV and NPY exports.

**Comment by axelboc** [comment]
Now that we have a proof of concept for TIFF export, we know we can do the same with CSV and NPY (and even replace the current CSV export feature on the Matrix vis so it's done server-side). The question is then: should we provide all three exports on _all_ visualizations? Or does TIFF only make sense on Heatmap/NxImage, CSV on Matrix, etc.?

From a UI standpoint, we can merge the export/snapshot toolbar controls into a single "Export" drop-down to save space. Which means that if we want to display all four exports (TIFF/CSV/NPY/snapshot) on all visualization, it's no problem at all.

**Comment by axelboc** [comment]
As per our discussion:

- `MatrixVis` : CSV ☑️ (to be delegated to H5Grove), NPY
- `LineVis` : CSV, NPY
- `HeatmapVis` : TIFF ✅ , NPY

Additional notes:

- When dimension sliders are visible, only the current slice is exported, not the entire dataset.
- NeXus visualizations, which could provide export features (either of the signal dataset only, or of the axes as well in the form of an x/y/data scatter format), are out of scope until users express the need for such export features.
