### ISSUE TITLE
Heatmap vis does not display data

### ISSUE THREAD

**Issue by t20100** [silx-kit/h5web#547]
With firefox-esr 78.8.0 on "rnice8" (debian 8), the heatmap vis displays all data as the minimum values and have some webgl errors.

![Screenshot from 2021-03-09 11-20-09](https://user-images.githubusercontent.com/9449698/110456187-8dc1c400-80c9-11eb-9288-5095d8142a88.png)

**Comment by axelboc** [comment]
I've downgraded Three to v0.117 so we get WebGL v1 by default. In doing so, I got the same behaviour locally as in the screenshot. It turned out to be because of `RedFormat`. Replacing it with `AlphaFormat` resolves the issue and removes the warning `texImage: Invalid internalformat`, which is also visible in the screenshot.

This makes me wonder whether we could make the visualisation work without downgrading Three and WebGL. We can make it work with WebGL 2 and the latest Three -- we'd still see all the other warnings, but the Heatmap would work (at least on Firefox 78). What do you think? Still better to switch to WebGL 1 for older versions of Firefox, perhaps?

**Comment by axelboc** [comment]
Here is a deployment of #548 : https://604758b92cba6f0008249b61--h5web.netlify.app/mock

**Comment by t20100** [comment]
Fixes the issue, great!

As for webgl2, I'm not sure. If it works with webgl1, I'd keep it for now and switch to webgl2 when required since full support of webgl apparently requires OpenGL4.3.
