### ISSUE TITLE
[Zoom] Give more zooming options

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#769]
### Example use case 
With a plot like this:
![image](https://user-images.githubusercontent.com/42204205/126961158-c88b4abf-0327-4709-9339-7699e4303c23.png)

I would like to be able to zoom on the y-axis while keeping the full x-axis. The current zoom only allows me to zoom on both axes at once.

### Implementation
We could imagine 
- Draw a zooming box with drag and drop ? This could interfere with the panning though.
- Zoom only on one axis with Alt/Ctrl+wheel ?
- Being able to zoom only on one axis by hovering on the desired axis and use the wheel

**Comment by axelboc** [comment]
- Drawing a rectangle to zoom horizontally doesn't make much sense to me. However, I do like UIs that allow selecting a horizontal area, like in the dev tools. However, in such UIs, the selection is usually displayed somewhere else on the UI -- i.e. it's not a zoom per se, more like an inspection.

    ![image](https://user-images.githubusercontent.com/2936402/128701278-1a9eaeff-0c99-46a8-b303-af5415cad06c.png)

    Assuming a zoom-as-you-select UI, it would indeed interfere with panning. We'd have to either bind the action to another mouse button (not discoverable) or add a button to the UI to switch between pan and select-to-zoom (tedious to use, one more button in the toolbar, and challenging labeling/iconography to convey that the button activates horizontal zooming as this pattern is more commonly used for x/y zooming).

- Ctrl+Wheel is tempting, but the problem is discoverability. We could add a help dialog somewhere to document all the interactions, but it's not great...

- Zooming by hovering on the desired axis is promising, as it is a lot more discoverable and doesn't require any additional UI. On the technical side, it may be difficult to make the axis system mesh communicate with the pan/zoom mesh.

- The simplest (technically) and clearest (for users), would be to add a button in the toolbar to change the behaviour of the wheel-zoom to horizontal-only. Compared to the select-to-zoom feature, it has the advantage of not drastically changing the interaction (mouse wheel to zoom) and not interfering with the pan. However, adding a button for this in the toolbar gives the feature a bit too much prominence for my taste. So far we only have buttons that control the display of the plot -- we don't have buttons that control the interactions with the plot. Perhaps interactions controls could be located somewhere else, like on the right of the plot title?

    ![image](https://user-images.githubusercontent.com/2936402/128704621-050e1d0d-ba6a-434a-81d7-c562c4c29e49.png)

---

One additional thing to keep in mind, is how this horizontal zoom is supposed to interact with the classic x/y zoom. Meaning, if the user has zoomed in on the plot on both x and y, what happens when they try to zoom in or out on y only? I could see the user getting into some pretty confusing zooming situations... 😅 Do we allow it, or do we reset the zoom when the user turns on horizontal zoom?

Also, if the switch between x/y zoom and horizontal zoom is too easy, it becomes error prone. For instance, with the hover-the-desired-axis solution, the user may inadvertently switch between x/y zooming and horizontal zooming by moving the mouse a tiny bit without meaning to.
