### ISSUE TITLE
Review attribute fetching to improve performance of processing of groups with many children

### ISSUE THREAD

**Issue by loichuder** [silx-kit/h5web#807]
## Problem

Opening a group with many children is slow. 

This was found to be the case for the `JupyterProvider` (see point 3. of https://github.com/silx-kit/jupyterlab-h5web/issues/51) and should be the same for `H5GroveProvider` and `HsdsProvider`.

## Reason

When processing a group, children are processed as well (https://github.com/silx-kit/h5web/blob/main/packages/app/src/h5web/providers/jupyter/jupyter-api.ts#L109). This processing triggers the fetching of attribute values **for each child**. This abundance of requests is the reason of the slowness.

## Proposed improvement

We could instead have a fetching on-demand of attribute values, removing the fetching of attribute values from the entity processing.

Attribute values are needed in the following scenarios:
1. When inspecting an entity (via `Inspect` button)
1. When processing a NX entity (as a `default` attribute could point to a `NXData` that needs to be displayed). This scenario can be discriminated without additional requests as the group metadata holds the child metadata that include the names of their attributes.

**Comment by axelboc** [comment]
In the end, we always fetch the values of all the attributes of an entity at once, even if we just need one. This doesn't seem to matter much with H5Grove, since it provides an endpoint for this, which is why I haven't gone further. It's more of a problem for HSDS, since the endpoint it provides only allows fetching the value of a single attribute, so we end up making consecutive requests to fetch all the values. I think this is fine for now -- we can optimise things later if the need arises.
